;ESTE PROGRAMA ES EL REPASO GENERAL DE CADA COSA  QUE HEMOS VISTO EN EL SEMESTRE

;LOS REGISTROS DE EL ENSAMBLADOR
;EN ENSAMBLADOR EXISTEN 4 REGISTROS PRINCIPALES, AX, BX, CX, DX
;ESTOS MISMOS SE CONFORMAN DE DOS REGISTROS, LOW REGISTER, HIGH REGISTER
;BASICAMENTE LOS REGISTROS SON BAJOS Y ALTOS, ESTOS TRABAJAN CON ESPACIOS DE 8 BITS, EN BINARIO SON LITERALMENTE 8 ESPACIOS (1010 0101)
;PERO PARA SACAR EL MAXIMO PROVECHO A ESOS ESPACIOS, SE DESARRROLLAN EN HEXADECIMAL, OSEA QUE NUESTRO VALOR MAXIMO ES 15D QUE ES F
;AHORA BIEN, PODEMOS MOVER CUALQUIER VALOR DE CUALQUIERO BASE SIEMPRE Y CUANDO DESPUES DEL VALOR, INMEDIATAMENTE PONGAMOS LA INICIAL DE LA BASE (B,O,D,H)
;CONCLUYENDO ESTA PRIMERA PARTE, DEBEMOS RECORDAR QUE EL MAXIMO VALOR QUE PUEDE TENER UN REGISTRO SON 16 BITS, ES DECIR, QUE NO PUEDE SOBREPASAR LOS VALORES MAS DE FFFF


;REGISTROS BAJOS

mov al,1010b
mov bl,37o
mov cl,99d
mov dl,0FFh ;CUANDO PONEMOS VALORES HEXADECIMALES PONEMOS UN 0 ANTES PARA QUE LA MAQUINA NO SE CONFUNDA

;REGISTROS ALTOS

mov ah,0ACh
mov bh,255d
mov ch,67o
mov dh,10100100b

;REGISTROS COMPLETOS

mov ax,0FFFFh
mov bx,177777o
mov cx,65535d
mov dx,1111111111111111b 


;LOS ULTIMOS REGISTROS, SON EL VALOR MAS GRANDE QUE TIENEN LOS REGISTROS DISPONIBLES, ES DECIR EL FAMOSO FFFF, RECORDANDO QUE LOS REGISTROS ESTAN EN BASE HEXADECIMAL
;PERO,¨QUE PASA SI NO PONEMOS LA BASE DEL NUMERO? PUES EL CODIGO LO TOMARA EN DECIMAL, Y ESTE LO CONVERTIRA EN HEXADECIMAL PARA PONERLO EN EL REGISTRO

mov ax,0000
mov bx,0000
mov cx,0000
mov dx,0000

;ASI SE LIMPIAN LOS REGISTROS DE UNA FORMA POCO FORMAL, POSTERIORMENTE VEREMOS UNA FORMA MAS LIMPIA DE HACERLO

;EJEMPLOS DEL CODIGO EN DECIMAL

mov al,255
mov ah,255

mov bx,2566

mov cl,100

mov dh,157

;SABIENDO ESTA INSTRUCCION COMO FUNCIONA, PODEMOS UTILIZAR OPERACIONES ARITMETICAS, RECORDANDO IMPORTANTEMENTE LA BASE DE DE LOS REGISTROS
;YA QUE UNA SUMA O RESTA NO ES IGUAL EN DECIMAL QUE EN HEXADECIMAL, (CUALQUIER BASE SE PUEDE REALIZAR SUMAS, RESTAS, ETC.)
;ALGO CURIOSO ES QUE SE PUEDEN REALIZAR SUMAS Y RESTAS CON DISTINTA BASE, ES DECIR SUMAR UN NUMERO DECIMAL COON UN NUMERO BINARIO Y EL RESULLTADO LO DARA EN HEXADECIMAL
;EL RESULTADO QUEDA DENTRO DEL REGISTRO, ES POR ESO QUE DARA EN HEXADECIMAL EL RESULTADO, DE CUALQUIER BASE QUE REALICES LA OPERACION

;INSTRUCCIONES ADD Y SUB
;LA INSTRUCCION ADD SIRVE PARA SUMAR CUALQUIER NUMERO EN REGISTROS
;LA INSTRUCCION SUB SIRVE PARA RESTAR CUALQUIER NUMERO EN REGISTRO

mov ax,0000
mov bx,0000
mov cx,0000
mov dx,0000